"""update organizer_request table

Revision ID: 1decd7c2c703
Revises: 1f8e51a99b7b
Create Date: 2026-06-30 11:38:32.865344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1decd7c2c703'
down_revision: Union[str, Sequence[str], None] = '1f8e51a99b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organizer_request_attachment',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['organizer_requests.request_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Organizer_request_attachment')
    # ### end Alembic commands ###
