"""add attachment table, fix users and organizer_requests

Revision ID: 1f8e51a99b7b
Revises: a3b6e1576a9f
Create Date: 2026-06-28 18:35:15.205088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8e51a99b7b'
down_revision: Union[str, Sequence[str], None] = 'a3b6e1576a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizer_requests', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('department_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department_name')
    op.drop_column('organizer_requests', 'create_at')
    # ### end Alembic commands ###
