"""update users table

Revision ID: 53eed12b4ec3
Revises: 4ede4401da92
Create Date: 2026-06-26 23:22:58.360644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53eed12b4ec3'
down_revision: Union[str, Sequence[str], None] = '4ede4401da92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Tạo enum types trước khi dùng trong các cột (PostgreSQL yêu cầu)
    userstatus_enum = sa.Enum('pending', 'active', 'rejected', name='userstatus')
    userstatus_enum.create(op.get_bind(), checkfirst=True)

    userrole_enum = sa.Enum('student', 'organizer', 'admin', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizer_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='organizerrequeststatus'), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.add_column('users', sa.Column('status', sa.Enum('pending', 'active', 'rejected', name='userstatus'), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('student', 'organizer', 'admin', name='userrole'),
               existing_nullable=True,
               postgresql_using='LOWER(role)::userrole')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('student', 'organizer', 'admin', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='role::varchar')
    op.drop_column('users', 'status')
    op.drop_table('organizer_requests')
    # Xoá enum types sau khi drop các cột dùng chúng
    sa.Enum(name='userstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='organizerrequeststatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
