"""update user table

Revision ID: 8eb4b751baac
Revises: 187921227c31
Create Date: 2026-07-25 13:13:04.478198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8eb4b751baac'
down_revision: Union[str, Sequence[str], None] = '187921227c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('events', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('events', 'registration_deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('events', 'file_url')
    op.alter_column(
        'users',
        'logo_url',
        new_column_name='avatar_url',
        existing_type=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'avatar_url',
        new_column_name='logo_url',
        existing_type=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.add_column('events', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('events', 'registration_deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
