"""add tables

Revision ID: a3b6e1576a9f
Revises: 53eed12b4ec3
Create Date: 2026-06-27 21:52:30.405986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b6e1576a9f'
down_revision: Union[str, Sequence[str], None] = '53eed12b4ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('event_status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED', name='event_status'), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['event_categories.category_id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_registrations',
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('registration_status', sa.Enum('REGISTERED', 'CHECKED_IN', 'CANCELLED', name='registration_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('registration_id')
    )
    op.create_table('notifications',
    sa.Column('noti_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('EVENT_UPDATED', 'EVENT_CANCELLED', 'NEW_EVENT', 'WAITLIST_PROMOTED', name='notification_type'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('noti_id')
    )
    op.create_table('saved_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'student_id')
    )
    op.create_table('waiting_list',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('join_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'student_id')
    )
    op.create_table('event_checkin_qr',
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('qr_token', sa.String(), nullable=True),
    sa.Column('manual_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.registration_id'], ),
    sa.PrimaryKeyConstraint('registration_id'),
    sa.UniqueConstraint('qr_token')
    )
    op.add_column('users', sa.Column('student_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['student_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'student_code')
    op.drop_table('event_checkin_qr')
    op.drop_table('waiting_list')
    op.drop_table('saved_events')
    op.drop_table('notifications')
    op.drop_table('event_registrations')
    op.drop_table('events')
    op.drop_table('event_categories')
    # ### end Alembic commands ###
